version: 2.1

executors:
  circleci_node:
    docker:
      - image: circleci/node:10

commands:
  npm_install:
    steps:
      - restore_cache:
          keys:
            - npm-cache-{{ .Environment.CACHE_KEY }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Environment.CACHE_KEY }}-
      - run: npm ci
      - save_cache:
          key: npm-cache-{{ .Environment.CACHE_KEY }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

workflows:
  on-commit:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    executor: circleci_node
    steps:
      - checkout
      - npm_install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: circleci_node
    steps:
      - attach_workspace:
          at: .
      - run: npm run build-release
      - run: |
          git config --global user.email "noreply@droidkaigi.jp" > /dev/null 2>&1
          git config --global user.name "CircleCI" > /dev/null 2>&1
      - add_ssh_keys:
          fingerprints:
            - "2f:9e:c4:56:49:d8:cf:aa:d1:1c:50:ce:d8:3e:96:97"
      - run: mkdir -p ~/.ssh; ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git fetch origin gh-pages:gh-pages
      - run: ./deploy.sh
